### ISSUE TITLE
Update to 7.8

### ISSUE THREAD

**Issue by ryanjmclaughlin** [chi-Ignition/generic-tcp-driver#2]
Any plans to update the module to 7.8?

**Comment by chi-Ignition** [comment]
The 7.8 release has been commited about 2 weeks ago (V2.8.3). Are there any problems with it?

**Comment by ryanjmclaughlin** [comment]
So sorry!!  I completely missed the release on the page.  I guess I need to catch up on my sleep and stop working on so many projects!  Thanks, and I'll let you know if I run into issues.
