### ISSUE TITLE
No Writeback Message for Server

### ISSUE THREAD

**Issue by msudol** [chi-Ignition/generic-tcp-driver#7]
Using 3.0.3 for 8.1.21 - I noticed in the help there is a tab for writeback message, but after installing the module and attempting to configure a test server, I don't see the writeback tab.  Is there a way to enable it?

**Comment by chi-Ignition** [comment]
The tab should be there. Is there any error message when you click on More->Config in the device?

**Comment by msudol** [comment]
No error messages, I have a working server listener and I've tested it with a basic TCP client connection - the status shows when its listening and when I'm connected.  (Still working out the intricacies of getting data to tags from the client, but it seems pretty straightforward).  

![image](https://github.com/chi-Ignition/generic-tcp-driver/assets/8793963/451fdded-9fd7-4ed2-9a94-1b03c709cb6a)

**Comment by chi-Ignition** [comment]
Did you possibly enable anonymous connections? In that mode, the driver does not know where to send a message,
![grafik](https://github.com/chi-Ignition/generic-tcp-driver/assets/6305639/c765743e-e4dc-4330-8328-19ea49659dcf)

**Comment by chi-Ignition** [comment]
Yes, there should be a tag folder for every alias with its own writeback tag.

Just as an info, i am not actively developing this driver anymore. So please don't rely on it in a production environment.

**Comment by msudol** [comment]
I forked it, was planning on writing something like this, but just getting started with the Ignition Module development API, so finding this was a godsend and should help me get my feet wet for putting together a TCP server driver. Thanks!
